import 'package:flutter/cupertino.dart';

const PRODUCTION_BASE_URL = '';
const PRE_PRODUCTION_BASE_URL = 'http://10.0.2.2:3255/';
const CLINTID = '9c3ZRTfD8zfs9wHknZFLp9ycYjG45lXBJftPoQSTbW4=';
const kPADDING = 8.0;
const kFirstTime = 'First Time';
const Duration kBaseSettleDuration = Duration(milliseconds: 246);
const SPACEING = 10.0;
const ROUNDED = 15.0;
const DRAWERLOGOASSETS = 'assets/images/wedding-ring.png';
const ONBORDINGSCREENASSETS = 'assets/images/onBordding';
const LOGOWHITEASSETS = 'assets/images/logowhite.png';
const LOGINLOGOASSETS = 'assets/images/ring.png';
const USERIMAGEASSETS = 'assets/images/userprofile.jpg';
const BACKGROUND = 'assets/images/top-view-blooming-flowers.jpg';
const FACEBOOKCOLOR = Color(0xFF1DA1F2);
const GOOGLECOLOR = Color(0xFFDB4437);
const APPLECOLOR = Color(0xFF555555);
const INSTAGRAMCOLOR = Color(0xFF8a3ab9);
